### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by c0d3z3r0** [C-Sto/gosecretsdump#2] opened 2019-12-02 10:57 UTC
Hi there!

First, ***THANK YOU***!!! I was able to extract a ntds file in 30 seconds that has been running over MONTHS in impacket's secretsdump :D

Any idea, what the issue is here (with another ntds file)?

~~~
XXX:$ gosecretsdump -system SYSTEM -ntds ntds.dit -status -out secretsdump.raw.txt
Writing to file  secretsdump.raw.txt
panic: unexpected EOF

goroutine 51 [running]:
github.com/c-sto/gosecretsdump/pkg/esent.(*Esedb).tagToRecord(0xc420078498, 0xc42000a200, 0xc422fda031, 0x1, 0x1fcf, 0x0)
        /home/XXX/go/src/github.com/c-sto/gosecretsdump/pkg/esent/conversion.go:19 +0xc9a
github.com/c-sto/gosecretsdump/pkg/esent.(*Esedb).GetNextRow(0xc420078498, 0xc42000a200, 0x4fe850, 0xa, 0x5d08c0)
        /home/XXX/go/src/github.com/c-sto/gosecretsdump/pkg/esent/ese.go:180 +0x2b5
github.com/c-sto/gosecretsdump/pkg/ditreader.(*DitReader).Dump(0xc420078400, 0x0, 0x0)
        /home/XXX/go/src/github.com/c-sto/gosecretsdump/pkg/ditreader/ditreader.go:115 +0x19b
github.com/c-sto/gosecretsdump/pkg/ditreader.(*DitReader).dump(0xc420078400)
        /home/XXX/go/src/github.com/c-sto/gosecretsdump/pkg/ditreader/ditreader.go:88 +0x2b
created by github.com/c-sto/gosecretsdump/pkg/ditreader.New
        /home/XXX/go/src/github.com/c-sto/gosecretsdump/pkg/ditreader/ditreader.go:45 +0x243
~~~

**Comment by c0d3z3r0** [comment] 2019-12-02 10:59
OS was Server 2012 R2

**Comment by C-Sto** [comment] 2019-12-02 12:14
Hey - glad it was useful for you!

That looks like an error that needs to be handled better. The tag to record conversion failed, which means either the .dit is broken (unlikely), or the parsing of tags has bugs (very likely). I happen to have a server 2012r2 DC available to me, so I'll quickly try and reproduce it.

**Comment by C-Sto** [comment] 2019-12-02 12:27
I wasn't able to reproduce, but the latest version should handle errors in that code slightly more elegantly. I expect the result will be a terminal full of errors, but there is a small chance that it will just error on one record, and then do the rest fine.. please let me know if this resolves anything, or makes it worse etc :)

**Comment by c0d3z3r0** [comment] 2019-12-02 12:54
Hah, nice! You partly solved it.
While I get a raw output file now (without Enabled/Disabled state) with the same count of accounts (after sort -u), the cleartext file is empty.

~~~
$ gosecretsdump -ntds ntds.dit -system SYSTEM -out out
Writing to file  out
Couldn't get row due to error:  Bad read, input data: 
error message:unexpected EOF
~~~

**Comment by C-Sto** [comment] 2019-12-02 12:57
are you expecting cleartext credentials? I assume you're comparing to a known-good output from the impacket version. Is there any other inconsistencies?

In the meantime I'll try and enable cleartext creds in my local DC, since they are stored differently in the .dit that could be where the bug lies

**Comment by c0d3z3r0** [comment] 2019-12-02 13:11
uh ouh ugh. Error on layer 8.... Enabled/Disabled state gets printed correctly when adding `-status`, which I simply forgot.

>are you expecting cleartext credentials?
no, and that's why it's empty. that's just fine, same problem as above :-)

> I assume you're comparing to a known-good output from the impacket version. Is there any other inconsistencies?

Yes, but the ntds.dit was extracted from a running system, which may be the cause of the original issue

**Comment by C-Sto** [comment] 2019-12-02 13:16
🙃 

I'm interested as to why the original crash occurred, but I'm not able to reproduce it. Can I consider this issue closed in that case?

**Closed** 2019-12-02 13:23 UTC

**Comment by c0d3z3r0** [comment] 2019-12-02 13:24
Issue is solved, yes. Well, unfortunately I can't share the ntds, but if you add a bunch of debugging functionality I'd be willing to help out finding the origin :)

**Comment by C-Sto** [comment] 2019-12-02 13:26
Of course, I understand. I plan on overhauling the output in the coming months, which should both increase speed and provide a bit easier verbosity selections. If I remember, I'll ping this issue again to see if you still have the file around :). Thanks again for the bug report!
